
services:
 
  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=Harshal@05

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host

    environment:
      - DATABASE_URL=postgresql://postgres:Harshal@05@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
    
 